### ISSUE TITLE
Bar chart and area graph showing different totals

### ISSUE THREAD

**Issue by jasonwhat** [spacedogXYZ/count-every-vote#5]
The bar chart is far lower than the actual early vote totals, which are correct in the original chart.

**Comment by jlev** [comment]
this is due to us taking the most recent value for in_person_2020 and mail_accept_2020 for the bar graph
the problem is that in_person_2020 is inconsistent, for some states it appeared to include early votes, but then the data dropped off around 10/23. 

For now I'll create a calculated column in_person_early_2020 which is equal to total_early_2020 - mail_accept_2020

We'll see if the in_person_2020 data comes back after election day totals are available

see 68611ec9fe73958d94d2fd59ecfd81b2fd412e8b for the details
